#Blurrings

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    blur {
       enabled = true
       size = 5
       passes = 2
       new_optimizations = true
       ignore_opacity = true
       xray = false
    }
}
