preload = ~/custom_wallpapers/photos/pexels-eberhardgross-1421903.jpg
preload = ~/custom_wallpapers/photos/pexels-messalaciulla-1162643.jpg
preload = ~/custom_wallpapers/photos/pexels-sebastian-palomino-933481-1955134.jpg

wallpaper = ,~/custom_wallpapers/photos/pexels-eberhardgross-1421903.jpg
wallpaper = ,~/custom_wallpapers/photos/pexels-messalaciulla-1162643.jpg
wallpaper = ,~/custom_wallpapers/photos/pexels-sebastian-palomino-933481-1955134.jpg

